export const PRODUCTDETAILS = {
  id: 1,
  link: "#",
  productName: "Branded T-Shirt",
  price: "$16.00",
  delPrice: "$21.00",
  productBadges: [
    {
      id: 1,
      label: "New",
      key: "new",
      value: "new",
      badge: "badge badge-link rounded-pill bg-primary",
      link: "",
      parentId: 1,
    },
    {
      id: 2,
      label: "Featured",
      key: "featured",
      value: "featured",
      badge: "badge badge-link rounded-pill bg-success",
      link: "",
      parentId: 1,
    },
    {
      id: 3,
      label: "Sale",
      key: "sale",
      value: "sale",
      badge: "badge badge-link rounded-pill bg-warning",
      link: "",
      parentId: 1,
    },
    {
      id: 4,
      label: "Popular",
      key: "popular",
      value: "popular",
      badge: "badge badge-link rounded-pill bg-info",
      link: "",
      parentId: 1,
    },
  ],
  imageOptions: [
    {
      id: 1,
      image: "assets/images/shop/product/s1.jpg",
      imageLink: "/productdetails",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      image: "assets/images/shop/product/s-1.jpg",
      imageLink: "/productdetails",
      order: 2,
      parentId: 1,
      imageStyle: "overlay-work",
    },
  ],
  colorIcons: [
    {
      id: 1,
      link: "#",
      colorStyle: "btn btn-icon btn-pills btn-soft-danger",
      icon: "heart",
      parentId: 1,
    },
    {
      id: 2,
      link: "/productdetails",
      colorStyle: "btn btn-icon btn-pills btn-soft-primary",
      icon: "eye",
      parentId: 1,
      margin: "mt-2",
    },
    {
      id: 3,
      link: "/shoppingcart",
      colorStyle: "btn btn-icon btn-pills btn-soft-warning",
      icon: "shopping-cart",
      parentId: 1,
      margin: "mt-2",
    },
  ],
  rating: [
    {
      id: 1,
      iconName: "mdi mdi-star",
      key: "1",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      iconName: "mdi mdi-star",
      key: "2",
      order: 2,
      parentId: 1,
    },
    {
      id: 3,
      iconName: "mdi mdi-star",
      key: "3",
      order: 3,
      parentId: 1,
    },
    {
      id: 4,
      iconName: "mdi mdi-star",
      key: "4",
      order: 4,
      parentId: 1,
    },
    {
      id: 5,
      iconName: "mdi mdi-star",
      key: "5",
      order: 5,
      parentId: 1,
    },
  ],
};
export const PRODUCTDETAILS3 = {
  id: 1,
  link: "#",
  productName: "Branded T-Shirt",
  price: "$16.00",
  delPrice: "$21.00",
  productBadges: [
    {
      id: 2,
      label: "Featured",
      key: "featured",
      value: "featured",
      badge: "badge badge-link rounded-pill bg-success",
      link: "",
      parentId: 1,
    },
  ],
  imageOptions: [
    {
      id: 1,
      image: "assets/images/shop/product/s12.jpg",
      imageLink: "/productdetails",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      image: "assets/images/shop/product/s-12.jpg",
      imageLink: "/productdetails",
      order: 2,
      parentId: 1,
      imageStyle: "overlay-work",
    },
  ],
  colorIcons: [
    {
      id: 1,
      link: "#",
      colorStyle: "btn btn-icon btn-pills btn-soft-danger",
      icon: "heart",
      parentId: 1,
    },
    {
      id: 2,
      link: "/productdetails",
      colorStyle: "btn btn-icon btn-pills btn-soft-primary",
      icon: "eye",
      parentId: 1,
      margin: "mt-2",
    },
    {
      id: 3,
      link: "/shoppingcart",
      colorStyle: "btn btn-icon btn-pills btn-soft-warning",
      icon: "shopping-cart",
      parentId: 1,
      margin: "mt-2",
    },
  ],
  rating: [
    {
      id: 1,
      iconName: "mdi mdi-star",
      key: "1",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      iconName: "mdi mdi-star",
      key: "2",
      order: 2,
      parentId: 1,
    },
    {
      id: 3,
      iconName: "mdi mdi-star",
      key: "3",
      order: 3,
      parentId: 1,
    },
    {
      id: 4,
      iconName: "mdi mdi-star",
      key: "4",
      order: 4,
      parentId: 1,
    },
    {
      id: 5,
      iconName: "mdi mdi-star",
      key: "5",
      order: 5,
      parentId: 1,
    },
  ],
};
export const PRODUCTDETAILS2 = {
  id: 1,
  link: "#",
  productName: "Earphones",
  price: "$16.00",
  delPrice: "$21.00",
  outOfStock: true,

  imageOptions: [
    {
      id: 1,
      image: "assets/images/shop/product/s5.jpg",
      imageLink: "/productdetails",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      image: "assets/images/shop/product/s-5.jpg",
      imageLink: "/productdetails",
      order: 2,
      parentId: 1,
      imageStyle: "overlay-work",
    },
  ],
  colorIcons: [
    {
      id: 1,
      link: "/productdetails",
      colorStyle: "btn btn-icon btn-pills btn-soft-primary",
      icon: "eye",
      parentId: 1,
      margin: "mt-2",
    },
  ],
  rating: [
    {
      id: 1,
      iconName: "mdi mdi-star",
      key: "1",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      iconName: "mdi mdi-star",
      key: "2",
      order: 2,
      parentId: 1,
    },
    {
      id: 3,
      iconName: "mdi mdi-star",
      key: "3",
      order: 3,
      parentId: 1,
    },
    {
      id: 4,
      iconName: "mdi mdi-star",
      key: "4",
      order: 4,
      parentId: 1,
    },
    {
      id: 5,
      iconName: "mdi mdi-star",
      key: "5",
      order: 5,
      parentId: 1,
    },
  ],
};

export const PRODUCTDETAILS4 = {
  id: 1,
  link: "#",
  productName: "Watch",
  price: "$16.00",
  delPrice: "$21.00",
  productBadges: [
    {
      id: 1,
      label: "New",
      key: "new",
      value: "new",
      badge: "badge badge-link rounded-pill bg-primary",
      link: "",
      parentId: 1,
    },
  ],
  imageOptions: [
    {
      id: 1,
      image: "assets/images/shop/product/s3.jpg",
      imageLink: "/productdetails",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      image: "assets/images/shop/product/s-3.jpg",
      imageLink: "/productdetails",
      order: 2,
      parentId: 1,
      imageStyle: "overlay-work",
    },
  ],
  colorIcons: [
    {
      id: 1,
      link: "#",
      colorStyle: "btn btn-icon btn-pills btn-soft-danger",
      icon: "heart",
      parentId: 1,
    },
    {
      id: 2,
      link: "/productdetails",
      colorStyle: "btn btn-icon btn-pills btn-soft-primary",
      icon: "eye",
      parentId: 1,
      margin: "mt-2",
    },
    {
      id: 3,
      link: "/shoppingcart",
      colorStyle: "btn btn-icon btn-pills btn-soft-warning",
      icon: "shopping-cart",
      parentId: 1,
      margin: "mt-2",
    },
  ],
  rating: [
    {
      id: 1,
      iconName: "mdi mdi-star",
      key: "1",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      iconName: "mdi mdi-star",
      key: "2",
      order: 2,
      parentId: 1,
    },
    {
      id: 3,
      iconName: "mdi mdi-star",
      key: "3",
      order: 3,
      parentId: 1,
    },
    {
      id: 4,
      iconName: "mdi mdi-star",
      key: "4",
      order: 4,
      parentId: 1,
    },
    {
      id: 5,
      iconName: "mdi mdi-star",
      key: "5",
      order: 5,
      parentId: 1,
    },
  ],
};
export const PRODUCTDETAILS5 = {
  id: 1,
  link: "#",
  productName: "Watch",
  price: "$16.00",
  delPrice: "$21.00",
  productBadges: [
    {
      id: 1,
      label: "New",
      key: "new",
      value: "new",
      badge: "badge badge-link rounded-pill bg-primary",
      link: "",
      parentId: 1,
    },
  ],
  imageOptions: [
    {
      id: 1,
      image: "assets/images/shop/product/s7.jpg",
      imageLink: "/productdetails",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      image: "assets/images/shop/product/s-7.jpg",
      imageLink: "/productdetails",
      order: 2,
      parentId: 1,
      imageStyle: "overlay-work",
    },
  ],
  colorIcons: [
    {
      id: 1,
      link: "#",
      colorStyle: "btn btn-icon btn-pills btn-soft-danger",
      icon: "heart",
      parentId: 1,
    },
    {
      id: 2,
      link: "/productdetails",
      colorStyle: "btn btn-icon btn-pills btn-soft-primary",
      icon: "eye",
      parentId: 1,
      margin: "mt-2",
    },
    {
      id: 3,
      link: "/shoppingcart",
      colorStyle: "btn btn-icon btn-pills btn-soft-warning",
      icon: "shopping-cart",
      parentId: 1,
      margin: "mt-2",
    },
  ],
  rating: [
    {
      id: 1,
      iconName: "mdi mdi-star",
      key: "1",
      order: 1,
      parentId: 1,
    },
    {
      id: 2,
      iconName: "mdi mdi-star",
      key: "2",
      order: 2,
      parentId: 1,
    },
    {
      id: 3,
      iconName: "mdi mdi-star",
      key: "3",
      order: 3,
      parentId: 1,
    },
    {
      id: 4,
      iconName: "mdi mdi-star",
      key: "4",
      order: 4,
      parentId: 1,
    },
    {
      id: 5,
      iconName: "mdi mdi-star",
      key: "5",
      order: 5,
      parentId: 1,
    },
  ],
};
