export const PRODUCTSDATA = [
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 37.3,
    description: "Vinyl Cleare Powder Free Gloves - S, 100/bx, 10bx/cs",
    id: 1,
    sku: "BMPF3004",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 100.0,
    description: "Biodegradable Nitrile Glove, XS, 200/bx, 10bx/cs",
    id: 2,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Shipping Cost",
    id: 3,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 257.0,
    description: "QFT Kit - 24 bx/case",
    id: 4,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Steel Walkers w/5" wheels, 4/cs',
    id: 53,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 95.12173,
    description: "Elbow Positioner, Immobilizer, 7x12.5in,..Youth Med, 12/cs",
    id: 54,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 86.64686,
    description:
      "Elbow Positioner, Immobilizer, Blue Purr Foam, w/Stays, 12/cs",
    id: 55,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 215.2494,
    description: "Board Arm 2x5 in, Pedi, 100/cs",
    id: 56,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 44.73186,
    description: "Board Arm 3 x 7in, Pedi, 12/cs",
    id: 57,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 54.0,
    description:
      "Elbow Positioner, Immobilizer, Blue Purr Foam, w/Metal Stays, 12/cs",
    id: 58,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 102.12157,
    description:
      "Elbow Positioner, Immobilizer, Blue Purr Foam, w/Metal Stays, 12/cs",
    id: 59,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 279.68,
    description: "Port Pack 5/cs",
    id: 60,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 213.3,
    description: "Biopsy Procedure Pack 9/cs",
    id: 61,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 192.99,
    description: "Neuro Tray 3/cs",
    id: 62,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0.75,
    description: "KN95 Face Mask-White",
    id: 63,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 102.25,
    description: '2 Button Folding Walker w/5" Wheels,..4/cs (Medline)',
    id: 64,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 238.56631,
    description: "Aluminum Tall Crutches, Medline, 8pr/cs",
    id: 65,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 170.0,
    description: "Clear Shields Protective Eyewear, Pre-assembled Dispense Box",
    id: 66,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 101.0,
    description: "Medzah Pre-Assembled Glasses, 10/bag, 10bags/cs",
    id: 67,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Aluminum, Adult Crutches, 8/case",
    id: 68,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Aluminum, Standard Walker with 5" wheels, 4/case',
    id: 69,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 52.8,
    description: 'Aluminum Two Button Walker w/5" Wheels, 4/case',
    id: 70,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Aluminum, Youth Crutches, 8/case",
    id: 71,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Aluminum, Tall Crutches, 8/case",
    id: 72,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Walker w/5" Wheels, 4/case',
    id: 73,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Aluminum, Standard Walker, 4/case",
    id: 74,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Cane, 20/case",
    id: 75,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Cane, 20/case",
    id: 76,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Cane, 10/case",
    id: 77,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Cane, 10/case",
    id: 78,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 51.2,
    description: "Aluminum Two Button Walker, 4/case",
    id: 79,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Aluminum Two Button Walker w/5" wheels, 4/case',
    id: 80,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Biodegradable Nitrile Glove, M, 200/bx, 10bx/cs",
    id: 81,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Biodegradable Nitrile Glove, L, 200/bx, 10bx/cs",
    id: 82,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Biodegradable Nitrile Glove, S, 200/bx, 10bx/cs",
    id: 83,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 80.0,
    description: "Biodegradable Nitrile Glove, XL, 200/bx, 10bx/cs",
    id: 84,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 37.36,
    description: "Vinyl Cleare Powder Free Gloves - M, 100/bx, 10bx/cs",
    id: 85,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Vinyl Cleare Powder Free Gloves - L, 100/bx, 10bx/cs",
    id: 86,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Vinyl Cleare Powder Free Gloves - S, 100/bx, 10bx/cs",
    id: 87,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Vinyl Cleare Powder Free Gloves - XL, 100/bx, 10bx/cs",
    id: 88,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 40.0,
    description: "MBO-Syringe, 50mL, Luer-Lok Tip, 40/bx",
    id: 89,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Bedpan, Fracture, Deluxe, Graphite, 24/cs",
    id: 90,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Basin, Emesis, Graphite, 500ml, 250/cs",
    id: 91,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 85.0,
    description: "Basic Synguard Nitrile Gloves-M, 100/bx, 10bx/cs",
    id: 92,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 105.0,
    description: "Caremax Youth Crutches, 10pr/cs",
    id: 93,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 105.0,
    description: "Caremax Adult Tall Crutches, 10pr/cs",
    id: 94,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 200.0,
    description: "Freeflex Sodium Chloride Bag 50mL, 60/cs",
    id: 95,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 140.0,
    description: "8.5MM Shiley Cuffed Trach Cannula",
    id: 96,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Dispenser Box Pre-Assembled Clear Shieldz",
    id: 97,
    sku: "MEDIT-506",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Trinity Nitrile Gloves, Small, 1000/CS",
    id: 98,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Trinity Nitrile Gloves, Medium, 1000/CS",
    id: 99,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Trinity Nitrile Gloves, Large, 1000/CS",
    id: 100,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Trinity Nitrile Gloves, X-Large, 1000/CS",
    id: 101,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 60.0,
    description: "Blue Surgical Masks, 2000/cs",
    id: 102,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 250.08,
    description: "89-6149.10 (Angiography Drape Pack 4/cs)",
    id: 103,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 464.17,
    description: "Picc Line Tray 9/cs",
    id: 104,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Amniocentesis Tray 20/cs",
    id: 105,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Steel Assembled Walker w/5 inch wheels (individual)",
    id: 106,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Red Apple Boot Covers, 110/cs",
    id: 107,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 225.0,
    description: 'Elbow Splint, 4x7", X-Small, 50/cs',
    id: 108,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 225.0,
    description: 'Elbow Splint, 6x9", Small, 50/cs',
    id: 109,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 225.0,
    description: 'Elbow Splint, 7x11.5" Medium, 50/cs',
    id: 110,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 275.0,
    description: 'Elbow Splint, 10x15.5", Large, 50/cs',
    id: 111,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 45.0,
    description: "Black Nitrile Exam Glove, S, 100/bx, 10bx/cs",
    id: 112,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 150.0,
    description: "Tube Track Sheridan Murphy Ciff 5.0MM",
    id: 113,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Syringe w/Cannula 800/cs",
    id: 114,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Board Arm 1 1/8 x2.5 in, Pedi, 100/cs",
    id: 115,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Pack Surg Splt Drp EENT, 1 Strl, 5/cs",
    id: 116,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Shiley Disposable Inner Cannula -Trachesostomy  Tube, 8.5mm",
    id: 117,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Standard Steel Commode(seat w/Lid,Bucket)4/cs",
    id: 118,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Board Arm 4x9in, Pedi, 25/cs",
    id: 119,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: '2 Button Folding Walker w/5"wheels, Junior, 4/cs',
    id: 120,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Jr.Wheeled Walker, 3"Wheels, 4/cs',
    id: 121,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Medium Crutches, 8pr/cs",
    id: 122,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "3M Film Dressings, 200/CS",
    id: 123,
    sku: "1626W",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Covid 19 Antigen Test Kits, Flow-Flex",
    id: 124,
    sku: "L031-118B5-300",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Exam Glove,M, 100/bx, 10bx/cs",
    id: 125,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Exam Glove, 100/bx, 10bx/cs",
    id: 126,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Exam Glove, XL, 100/bx, 10bx/cs",
    id: 127,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Exam Glove, XXL, 100/bx, 10bx/cs",
    id: 128,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Absorbent Pouch, 1 Bay, 2.4x5.1", 30ml, 3000/cs',
    id: 129,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Abosrbent Pouch, 2 Bay, 3.5x5.1", 60ml, 1800/cs',
    id: 130,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Absorbent Sheet, 6x6"',
    id: 131,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Absorbent Sheet, 12x12", 450/cs',
    id: 132,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Bubble Bags with Adhesive, 3"x5"',
    id: 133,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: 'Bubble Bags with Adhesive, 4"x5.5"',
    id: 134,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 16.69,
    description: "Urine Cup 8oz w/Lid, 500/case",
    id: 135,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 42.0,
    description: "Wire Box Hangar",
    id: 136,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Specimen Container 3oz/90ml, Tamper Evident SEal, 400/cs",
    id: 137,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Maternit NIPT Single Pack Box",
    id: 138,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "CF Plus Combo Kit Box",
    id: 139,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description:
      "Instant Hot Pack, magnesium sulfate activated hot pack, 24pks/cs",
    id: 140,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description:
      "Instant Ice Pack, ammonium nitrate activated cold pack, 24pks/cs",
    id: 141,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Alcohol Prep Pad Medium 1/pc, 200pcs/box, 25bx/cs",
    id: 142,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Alcohol Prep Pad Large, 1/pouch,100pouches/bx, 10bx/cs",
    id: 143,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description:
      "Dukal Shoe Covers, Non Skid, One Size Fits All, Blue, 100/bg, 10 bg/cs",
    id: 144,
    sku: "350-10",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "FlowFlex Covid Tests 288/cs",
    id: 145,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Gloves, S, 100/bx, 10bx/cs",
    id: 146,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Gloves, M, 100/bx, 10bx/cs",
    id: 147,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Gloves, L, 100/bx, 10bx/cs",
    id: 148,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Gloves, XL, 100/bx, 10bx/cs",
    id: 149,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Black Nitrile Gloves, XXL, 90/bx, 10bx/cs",
    id: 150,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Covid Test kits, flow flex. EA",
    id: 152,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Dispenser Box Bracket",
    id: 153,
    sku: "23-507",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Footprint Polyurethane Umbilical Catheters",
    id: 154,
    sku: "P2UVC3.5",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "3M Steri Strip Benzion",
    id: 155,
    sku: "C1544",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Basic Synguard Nitrile, S, 100/bx, 10bx/cs",
    id: 156,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "ELECTRODE MONITORING REPOSITIONABLE 1.56INX1.25IN RED DOT",
    id: 157,
    sku: "2670-5",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 17.4,
    description:
      "EO Sterile Gauze Sponge, 8ply, 2pcs/pouch; 50pouches/box; 30boxes/case",
    id: 158,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 16.0,
    description: "Vinyl Synmax Exam Gloves",
    id: 159,
    sku: "BMPF3003",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 16.0,
    description: "Vinyl Synmax Exam Gloves Medium",
    id: 160,
    sku: "BMPF3002",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 16.0,
    description: "Vinyl Synmax Exam Gloves Large",
    id: 161,
    sku: "BMPF3003",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 16.0,
    description: "Vinyl Synmax Gloves X-Large",
    id: 162,
    sku: "BMPF3004",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 14.0,
    description: "Youth Aluminum Crutches, PR",
    id: 163,
    sku: "LYN-0814-01-EA",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 14.0,
    description: "Adult Medium Aluminum Crutches Medium, PR",
    id: 164,
    sku: "LYN-0814-02-EA",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 14.0,
    description: "Youth Aluminum Crutches Tall, PR",
    id: 165,
    sku: "LYN-0814-03-EA",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Basic Synguard Nitrile Gloves, XL",
    id: 166,
    sku: "NGPF-7004-XL",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 80.0,
    description: "jkhkjhkj",
    id: 167,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 45.0,
    description: "Basic Synguard Gloves, L, 100/bx, 10bx/cs",
    id: 168,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Baxter Irrigation Solution Sodium Chloride, 1000ML, 12/CS",
    id: 169,
    sku: "2F7124",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Baxter Tubing Sets",
    id: 170,
    sku: "2R8519",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Medline Aluminum Standard Canes",
    id: 171,
    sku: "MDS86415",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "BD Vacutainer® One-Use Holder",
    id: 172,
    sku: "364815",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Dukal Bouffant Caps",
    id: 173,
    sku: "321-10",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Skin Prep Solution ChloraPrep™ Clear 3 mL Foam Applicator 2%",
    id: 174,
    sku: "930400",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description:
      "Skin Prep Solution ChloraPrep™ Hi-Lite Orange™ 3 mL Foam Applicator 2%",
    id: 175,
    sku: "930415",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "3m 1860 masks",
    id: 176,
    sku: "1860",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 49.0,
    description: "Vyaire 100ml NACL Solution",
    id: 177,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 49.0,
    description:
      "Vyaire Irrigation Solution AirLife® 0.9% Sodium Chloride Not for Injection Bottle 100 m",
    id: 178,
    sku: "al4109",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Safety Zone XXL Vinyl Gloves",
    id: 179,
    sku: "GVP9-2X-1-BL",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 35.0,
    description: "Vinyl Gloves XXL, 100/cs, 10bx/cs",
    id: 180,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "b Braun 500ML Sterile water, 16/CS",
    id: 181,
    sku: "R5001-01",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Pivoting Clipper Blade Assembly 3M™ Single Use",
    id: 182,
    sku: "9660",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Specialty Clipper Blade Assembly 3M™ Single Use",
    id: 183,
    sku: "9690",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 80.0,
    description: "Halyad Gloves, 250/bx, 10bx/case, L",
    id: 184,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Genabio Covid test kits, 252/CS",
    id: 185,
    sku: "UMRA9-E00301",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Carefusion Surgical Clipper Contoured / Tapered Head, EA",
    id: 186,
    sku: "5513E",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description:
      "Charging Adapter CareFusion For SensiClip®Surgical Clippers, EA",
    id: 187,
    sku: "5514A",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Surgical Clipper Blade CareFusion, 50/CS",
    id: 188,
    sku: "4406",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "icemelt",
    id: 189,
    sku: "icemelt",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Irrigation Solution Sterile Water for Irrigation",
    id: 190,
    sku: "R5000-01",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Irrigation Solution 0.9% Sodium Chloride",
    id: 191,
    sku: "R5200-01",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 18.0,
    description: "Huayuan Vinyl Gloves, S, 100/bx, 10bx/cs",
    id: 192,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 16.49,
    description: "25 PR of LARGE Gloves with 25 mask",
    id: 193,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 16.49,
    description: "25 PR of MEDIUM Gloves with 25 mask",
    id: 194,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 16.49,
    description: "25 PR of SMALL Gloves with 25 mask",
    id: 195,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 46.79,
    description: "PCA kit with Covid test - Small",
    id: 196,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 46.79,
    description: "PCA kit with Covid test - Medium",
    id: 197,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 46.79,
    description: "PCA kit with Covid test - Large",
    id: 198,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Brackets for dispenser box",
    id: 199,
    sku: "WBH-001",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Huayuan Vinyl Gloves, L, 100/bx, 10bx/case",
    id: 200,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Huayuan Vinyl Gloves, M, 100/bx, 10bx/cs",
    id: 201,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description:
      "Secondary IV Administration Set Clearlink™ Gravity Without Ports 10 Drops / mL Drip Rate",
    id: 202,
    sku: "2H7462",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Dukal Beard Covers, 1000/CS",
    id: 203,
    sku: "361",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Aspiration/Injection Disc Filter Supor",
    id: 204,
    sku: "415008",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Spike Adapter, 50/CS",
    id: 205,
    sku: "418105",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 80.0,
    description: "Glove Nitrile",
    id: 206,
    sku: "",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Cardinal 14 Inch Suction Catheter",
    id: 207,
    sku: "CC4681AH",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "Vyaire General Purpose Probes, 50/CS",
    id: 208,
    sku: "M1024229VY",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "IV Pump Set Clearlink™ Pump 3 Ports 10 Drops",
    id: 209,
    sku: "2R8537",
  },
  {
    image: "assets/images/shop/product/s12.jpg",
    Price: 0e-9,
    description: "IV Filter Aspiration",
    id: 210,
    sku: "PF5000",
  },
];
